### ISSUE TITLE
mtl compatibility

### ISSUE THREAD

**Issue by deepfire** [robrix/fused-effects#99]
In practical scenarios it's often required to combine `fused-effects` with `mtl`-based stacks.

As an example, let's imagine having an involved transformer stack that we'd like to run our `fused-effects` stack on top of -- while also transparently using the operations from the underlying transformer _in the `fused-effects` stack_.

Is this currently possible -- at least for pure `fused-effects`, like `Reader`?

Case in point:
```
doit ∷ (MonadIO m) ⇒ m (String, String)
doit =
  MTL.runReaderT (do
    liftIO $ runM $ runReader "quux" $ do
      liftIO $ putStrLn "foo"
      foo ← MTL.ask
      bar ← ask
      pure (foo, bar))
    ["bar"]
```
->
```
error:
    • Couldn't match type ‘MTL.ReaderT String m0’
                     with ‘Eff (ReaderC r0 (Eff (LiftC IO)))’
      Expected type: Eff (ReaderC r0 (Eff (LiftC IO))) String
        Actual type: MTL.ReaderT String m0 String
    • In a stmt of a 'do' block: foo <- MTL.ask
      In the second argument of ‘($)’, namely
        ‘do liftIO $ putStrLn "foo"
            foo <- MTL.ask
            bar <- ask
            return (foo, bar)’
      In the second argument of ‘($)’, namely
        ‘runReader "quux"
           $ do liftIO $ putStrLn "foo"
                foo <- MTL.ask
                bar <- ask
                return (foo, bar)’
```

**Comment by robrix** [comment]
I think #82 and #98 are both relevant:

1. We should have some smart constructor for the `Lift` effect aside from the `MonadIO` instance (#82). That seems pretty obviously desirable, tho in the meantime you can accomplish it with `sendM m = send (Lift (fmap pure m))`.

2. We should have some way to constrain ambiguity stemming from uses of `Lift m` where `m` is polymorphic by requiring the `Lift` effect to be the last `Member` in the signature (#98). That came up specifically with `MonadIO` constraints, but it applies more generally: if an effect has a type parameter, you can run into clumsy/frustrating ambiguous type errors in code which is or could be polymorphic. (e.g. `modify succ` when you have `Member (State Int) sig` will error because `succ` doesn’t determine `s ~ Int`).

**Comment by deepfire** [comment]
Thank you @robrix -- so we have hope, after all! : -)

..and also thank you for the workaround!

**Comment by robrix** [comment]
@deepfire: Ah, that’s a _third_ thing: defining `MonadReader`, `MonadState`, etc. instances for `Eff`. There are two problems with that:

1. We can’t define those with `Member` constraints because they won’t uniquely determine the functional parameters. E.g. `instance (Carrier sig m, Member (Reader r) sig) => MonadReader r (Eff m)` can’t determine `r` from `m`. There might be something analogous to a `LastMember` constraint that we could do for this; IIRC Oleg tackled this with extensible effects at one point and his approach might work for us as well.

2. Even if we had a functioning `MonadReader` instance, `MTL.ask` would be sent to the `ReaderC` carrier, not the lifted `ReaderT IO` inside it, because the `ReaderC` wraps it. (The same can be seen to happen if you have e.g. `Eff (ReaderC Int (Eff (ReaderC Int m)))`—`fused-effects`’ `ask` will be intercepted by the outer `ReaderC`, not the inner one.) IMO that’s a bug in the example code you give—if you want to use `MTL.ask` on the `m` lifted inside the `Eff (ReaderC String …)`, then you should use something like `sendM`.

**Comment by deepfire** [comment]
@robrix, I'm also thinking about complex monad stacks, like Reflex -- e.g. a combination of:

- https://github.com/reflex-frp/reflex/blob/develop/src/Reflex/Class.hs#L336
- https://github.com/reflex-frp/reflex/blob/develop/src/Reflex/TriggerEvent/Class.hs#L20
- https://github.com/reflex-frp/reflex/blob/develop/src/Reflex/PerformEvent/Class.hs#L29

Practically, to use Reflex I have to have this constraint signature:

```
type TheoroughlyReflexive t m
  = ( MonadFix m
    , MonadHold t m
    , PostBuild t m
    , MonadIO m
    , PerformEvent t m
    , Ref m ~ Ref IO
    , MonadIO (Performable m)
    , Typeable t
    )
```

**Comment by deepfire** [comment]
@robrix, thank you a lot!  I'll try to go along the way you suggest. : -)

**Comment by robrix** [comment]
> Now, the question is whether it'll be possible to interleave the "sending", so to speak, with the `Eff`'s effects -- i.e. will the `Eff`s effect stack be accessible inside `sendM`?

If you want to use `fused-effects`’ effects, you have to have a `Carrier` constraint for the context and a `Member` constraint for the carrier’s signature. If you had those for whatever monad you’re lifting with the `Lift` effect, then you wouldn’t need the `Lift` effect at all.

Equivalently, a monad `m` lifted into a monad transformer `t m` can’t use `t m`’s functionality; `lift (action :: m a) :: t m a`, i.e. `action`’s type doesn’t mention `t` so it can’t do anything which requires `t`, only things which only require `m`.

If, on the other hand, you wanted to have some monad transformer wrapping a `fused-effects` computation, you could do that with something like `FooT (Eff carrier)`. Then the outer context could be given a (possibly orphan) `Carrier` instance and send requests to `Eff`, but the inner `Eff` context couldn’t send requests to `FooT` (because it doesn’t contain it).

As to which layering is _correct_, that really depends on the semantics you want, e.g. `Eff (ErrorC e (Eff (StateC s m)))` and `Eff (StateC s (Eff (ErrorC e m)))` have different semantics: in the former, errors discard state, in the latter, errors do not. (And the variations in meaning of layers of `State` carriers above and below `NonDet` carriers are even more interesting.)

**Comment by deepfire** [comment]
I'm struggling to come up with a `sendM` definition that would work for:
> instance (Carrier sig m, Member (Lift n) sig) => MonadIO (Blah n m) where liftIO = sendM

**Comment by robrix** [comment]
@deepfire: this worked for me:

```haskell
newtype Blah (n :: * -> *) m a = Blah { runBlah :: Eff m a }
  deriving (Applicative, Functor, Monad)

instance (Carrier sig m, Member (Lift n) sig, MonadIO n) => MonadIO (Blah n m) where
  liftIO = send . Lift . fmap pure . liftIO @n

instance Carrier sig m => Carrier sig (Blah n m) where
  ret = Blah . ret
  eff = Blah . eff . handleCoercible
```

I’ve used `ScopedTypeVariables` to bring `n` into scope in the `MonadIO` instance, and `TypeApplications` to constrain the inner `liftIO` call to operate on `n`. You can use a type annotation instead of the type application, but it’s more verbose.

**Comment by deepfire-pusher** [comment]
@robrix, thank you a lot, again!

**Comment by robrix** [comment]
@deepfire @deepfire-pusher: You’re very welcome! In light of #82 & #98, I’m going to close this out now, but thank you for using the lib and I hope you enjoy it!
